### ISSUE TITLE
Thresholding for different regions

### ISSUE THREAD

**Issue by hassanimran304** [BlueFish6543/dna-imaging#4]
Different regions can have different threshold values. Ladder region can have a lower threshold as it is unlikely to be smeared.

**Comment by hassanimran304** [comment]
Possible better way for thresholding is to first apply a uniform threshold for the image. However that will result in smears being considered as well, so we can apply the algorithm again within each contour to get rid of the smearing.

**Comment by BlueFish6543** [comment]
Currently having different thresholds for the ladder region and the rest of the image, on the `dev` branch
